DATASET_ARTIFACT_TYPE = 'dataset'
DATASET_MODEL_TYPE = 'model'
WEIGHTS_FILENAME = 'weights.pth'

LOSS = 'loss'
ACCURACY_PCT = 'acc_pct'
ACCURACY_FRAC = 'acc_frac'
EPOCH = 'n_epochs'
EXAMPLE = 'n_examples'
OPTIMIZER = 'optimizer'
BATCH_SIZE = 'batch_size'
LR = 'lr'
DROPOUT_RATE = 'dropout_rate'
